version: '3'
 
services:
  app:
    build:
      context:  ./chatR
      dockerfile: Dockerfile
    expose:
      - "5000"
 
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    links:
      - app